kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: composer:latest
    commands:
      - cd app
      - composer install
    when:
      branch:
        - main

  - name: deploy-to-volume
    image: busybox:latest
    commands:
      - cd app
      - mkdir -p /var/www/dencode
      - rm -rf /var/www/dencode/*
      - cp -r . /var/www/dencode/
    when:
      branch:
        - main

node:
  location: nexus
