kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: composer:latest
    commands:
      - cd app
      - composer install

  - name: deploy-to-volume
    image: busybox:latest
    commands:
      - cd app
      - rm -rf /var/www-dencode/*
      - cp -r . /var/www-dencode/

node:
  location: nexus
