
services:
  dencode-nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - dencode-php

  dencode-php:
      image: php:8-fpm
      volumes:
        - ../app:/var/www/html

networks:
  default:
    name: dencode-network
